import type { Module } from './types';

const midterm2: Module = {
  id: 'midterm-2',
  slug: 'midterm-2',
  title: 'Midterm Test 2',
  description: 'Covers Classes & Objects and Stacks & Queues (Modules 3–4).',
  icon: '📋',
  color: 'from-rose-500 to-pink-400',
  locked: true,
  isMidterm: true,
  lessons: [],
  questions: [
    // ── 5 MCQ ─────────────────────────────────────────────────────────────
    {
      id: 'mt2-q1',
      type: 'multiple-choice',
      prompt: 'What is the output?\n\n```python\nclass Dog:\n    species = "Canis familiaris"\n\n    def __init__(self, name):\n        self.name = name\n\nd1 = Dog("Rex")\nd2 = Dog("Buddy")\nd1.species = "Wolf"\nprint(d2.species)\n```',
      choices: [
        { id: 'a', text: 'Wolf' },
        { id: 'b', text: 'Canis familiaris' },
        { id: 'c', text: 'None' },
        { id: 'd', text: 'AttributeError' },
      ],
      correctAnswer: 'b',
      explanation: 'Setting d1.species = "Wolf" creates an instance attribute on d1 only — it does not modify the class attribute. d2 has no instance attribute, so it reads the class attribute "Canis familiaris".',
    },
    {
      id: 'mt2-q2',
      type: 'multiple-choice',
      prompt: 'What is printed?\n\n```python\nclass Animal:\n    def speak(self):\n        return "..."\n\nclass Cat(Animal):\n    def speak(self):\n        return "Meow"\n\na = Animal()\nc = Cat()\nprint(a.speak())\nprint(c.speak())\n```',
      choices: [
        { id: 'a', text: '...\n...' },
        { id: 'b', text: 'Meow\nMeow' },
        { id: 'c', text: '...\nMeow' },
        { id: 'd', text: 'Meow\n...' },
      ],
      correctAnswer: 'c',
      explanation: 'Animal.speak() returns "...". Cat overrides speak() to return "Meow". Each object calls its own version — a.speak() → "...", c.speak() → "Meow".',
    },
    {
      id: 'mt2-q3',
      type: 'multiple-choice',
      prompt: 'You push 1, 2, 3, 4, 5 onto a Stack (1 first). You call `pop()` three times. What does the next `peek()` return?',
      choices: [
        { id: 'a', text: '5' },
        { id: 'b', text: '1' },
        { id: 'c', text: '2' },
        { id: 'd', text: '3' },
      ],
      correctAnswer: 'c',
      explanation: 'After pushing 1–5, top is 5. Three pops remove 5, 4, 3. The stack is now [1, 2] with 2 on top. peek() returns 2.',
    },
    {
      id: 'mt2-q4',
      type: 'multiple-choice',
      prompt: 'What is the output?\n\n```python\nfrom collections import deque\n\nq = deque()\nq.append("a")\nq.append("b")\nq.append("c")\nq.dequeue()\nq.append("d")\nprint(q[0])\n```',
      choices: [
        { id: 'a', text: 'a' },
        { id: 'b', text: 'b' },
        { id: 'c', text: 'c' },
        { id: 'd', text: 'd' },
      ],
      correctAnswer: 'b',
      explanation: 'After appending a, b, c: deque is [a, b, c]. popleft() removes a → [b, c]. Append d → [b, c, d]. q[0] is the front element: "b".',
    },
    {
      id: 'mt2-q5',
      type: 'multiple-choice',
      prompt: 'A circular queue has capacity 5. After these operations — enqueue(A), enqueue(B), enqueue(C), dequeue(), dequeue(), enqueue(D), enqueue(E), enqueue(F) — what is the size?',
      choices: [
        { id: 'a', text: '3' },
        { id: 'b', text: '4' },
        { id: 'c', text: '5' },
        { id: 'd', text: '2' },
      ],
      correctAnswer: 'b',
      explanation: 'Start: enqueue A, B, C → size 3. Dequeue twice → size 1 (C remains). Enqueue D, E, F → size 4. The capacity of 5 is not exceeded.',
    },

    // ── 10 Code Challenges ────────────────────────────────────────────────
    {
      id: 'mt2-q6',
      type: 'code-challenge',
      language: 'python',
      prompt: 'Define a `Rectangle` class with `__init__(self, width, height)`. Add an `area()` method and a `perimeter()` method. Add `__str__` returning `"Rectangle(W x H)"`. Create `Rectangle(6, 4)` and print it, its area, and its perimeter.',
      starterCode: '',
      expectedOutput: 'Rectangle(6 x 4)\n24\n20',
      correctAnswer: '__code__',
      explanation: 'area returns width*height. perimeter returns 2*(width+height). __str__ returns f"Rectangle({self.width} x {self.height})".',
    },
    {
      id: 'mt2-q7',
      type: 'code-challenge',
      language: 'python',
      prompt: 'Create a `BankAccount` class with `__init__(self, owner, balance=0)`. Add `deposit(amount)`, `withdraw(amount)` (reject if insufficient funds — print `"Insufficient funds"` and do not change the balance), and `__str__` returning `"owner: $balance"`. Create bank account with owner Alice, Deposit 1000, withdraw 300, withdraw 800, then print the account.',
      starterCode: '',
      expectedOutput: 'Insufficient funds\nAlice: $700',
      correctAnswer: '__code__',
      explanation: 'deposit: self.balance += amount. withdraw: if amount > self.balance: print("Insufficient funds"); else: self.balance -= amount. After +1000, -300 (balance=700), -800 is rejected.',
    },
    {
      id: 'mt2-q8',
      type: 'code-challenge',
      language: 'python',
      prompt: 'Create a `Counter` class with `__init__(self, start=0)`. Add `increment()` (+1), `decrement()` (-1, but never below 0), `reset()` (back to 0), and `value` as a property (or just a readable attribute). Create a counter, increment 5 times, decrement 2 times, print the value, reset, print the value.',
      starterCode: '',
      expectedOutput: '3\n0',
      correctAnswer: '__code__',
      explanation: 'increment: self._count += 1. decrement: if self._count > 0: self._count -= 1. reset: self._count = 0. After 5 increments and 2 decrements, value is 3.',
    },
    {
      id: 'mt2-q9',
      type: 'code-challenge',
      language: 'python',
      prompt: 'Create a `Shape` base class with `area()` returning 0. Create `Circle(Shape)` with `__init__(self, radius)` that overrides `area()` returning `3.14159 * radius ** 2` (rounded to 2 decimal places). Create `Square(Shape)` with `__init__(self, side)` that overrides `area()`. Print the area of `Circle(5)` and `Square(4)`.',
      starterCode: '',
      expectedOutput: '78.54\n16',
      correctAnswer: '__code__',
      explanation: 'Circle.area: return round(3.14159 * self.radius ** 2, 2). Square.area: return self.side ** 2. Polymorphism — each subclass provides its own area implementation.',
    },
    {
      id: 'mt2-q10',
      type: 'code-challenge',
      language: 'python',
      prompt: 'Implement a `Stack` class using a Python list with `push(item)`, `pop()` (return `None` if empty), `peek()` (return `None` if empty), `is_empty()`, and `size()`. Push "a", "b", "c". Print `peek()`, `pop()`, `size()`.',
      starterCode: '',
      expectedOutput: 'c\nc\n2',
      correctAnswer: '__code__',
      explanation: 'push: self._items.append(item). pop: return self._items.pop() if not empty else None. peek: return self._items[-1] if not empty else None. size: return len(self._items).',
    },
    {
      id: 'mt2-q11',
      type: 'code-challenge',
      language: 'python',
      prompt: 'Use a stack (Python list) to reverse a string. Write `reverse_string(s)` — push each character, then pop all into a result string. Print `reverse_string("algorithm")` and `reverse_string("stack")`.',
      starterCode: '',
      expectedOutput: 'mhtirogla\nkcats',
      correctAnswer: '__code__',
      explanation: 'stack = []. for char in s: stack.append(char). result = "". while stack: result += stack.pop(). return result.',
    },
    {
      id: 'mt2-q12',
      type: 'code-challenge',
      language: 'python',
      prompt: 'Write `is_balanced(s)` using a stack. Return `True` if all `(`, `[`, `{` are properly closed in order. Print `is_balanced("({[]})")`, `is_balanced("([)]")`, `is_balanced("{[]")`.',
      starterCode: '',
      expectedOutput: 'True\nFalse\nFalse',
      correctAnswer: '__code__',
      explanation: 'stack=[]. matching={")":"(", "]":"[", "}":"{"}. For each char: push openers, for closers check stack not empty and stack.pop()==matching[char] else return False. Return len(stack)==0.',
    },
    {
      id: 'mt2-q13',
      type: 'code-challenge',
      language: 'python',
      prompt: 'Implement a `Queue` class using a Python list with `enqueue(item)`, `dequeue()` (return `None` if empty), `front()` (return `None` if empty), `is_empty()`, `size()`. Enqueue 10, 20, 30. Print `front()`, `dequeue()`, `size()`.',
      starterCode: '',
      expectedOutput: '10\n10\n2',
      correctAnswer: '__code__',
      explanation: 'enqueue: self._items.append(item). dequeue: return self._items.pop(0) if not empty else None. front: return self._items[0] if not empty else None.',
    },
    {
      id: 'mt2-q14',
      type: 'code-challenge',
      language: 'python',
      prompt: 'Write `evaluate_postfix(expr)` that evaluates a postfix (RPN) expression string using a stack. Tokens are space-separated. Operands are integers, operators are `+`, `-`, `*`. Print `evaluate_postfix("3 4 +")` and `evaluate_postfix("5 1 2 + 4 * + 3 -")`.',
      starterCode: '',
      expectedOutput: '7\n14',
      correctAnswer: '__code__',
      explanation: 'Split expr. For each token: if digit push int(token). If operator pop b then a (order matters), push a op b. Return stack[0]. "5 1 2 + 4 * + 3 -" → 5 + (1+2)*4 - 3 = 5+12-3 = 14.',
    },
    {
      id: 'mt2-q15',
      type: 'code-challenge',
      language: 'python',
      prompt: 'Implement a `CircularQueue` class with `__init__(self, capacity)`, `enqueue(item)` (print `"Queue full"` if at capacity), `dequeue()` (return `None` if empty), `size()`. Use a list with front/back pointers and modulo wrapping. Create capacity-3 queue, enqueue 1, 2, 3, try enqueue 4, dequeue, enqueue 5, print size.',
      starterCode: '',
      expectedOutput: 'Queue full\n3',
      correctAnswer: '__code__',
      explanation: 'Use self._data=[None]*cap, self._front=0, self._back=0, self._size=0. enqueue: if size==capacity print "Queue full" else place item at _back, _back=(_back+1)%cap, _size+=1. dequeue: take _data[_front], _front=(_front+1)%cap, _size-=1. After enqueue 1,2,3 (full), enqueue 4 prints "Queue full", dequeue removes 1, enqueue 5 → size=3.',
    },
  ],
};

export default midterm2;
