import type { Module } from './types';

const midterm1: Module = {
  id: 'midterm-1',
  slug: 'midterm-1',
  title: 'Midterm Test 1',
  description: 'Covers Testing & Exceptions, Algorithm Complexity, and Searching & Sorting (Modules 0–2).',
  icon: '📝',
  color: 'from-violet-500 to-purple-400',
  locked: false,
  isMidterm: true,
  lessons: [],
  questions: [
    // ── 5 MCQ ─────────────────────────────────────────────────────────────
    {
      id: 'mt1-q1',
      type: 'multiple-choice',
      prompt: 'What is the output of the following code?\n\n```python\ntry:\n    x = int("abc")\nexcept ValueError:\n    print("caught")\nfinally:\n    print("done")\n```',
      choices: [
        { id: 'a', text: 'caught' },
        { id: 'b', text: 'done' },
        { id: 'c', text: 'caught\ndone' },
        { id: 'd', text: 'An unhandled exception crashes the program' },
      ],
      correctAnswer: 'c',
      explanation: 'int("abc") raises ValueError. The except block catches it and prints "caught". The finally block always runs, so "done" prints next. Output is "caught" then "done".',
    },
    {
      id: 'mt1-q2',
      type: 'multiple-choice',
      prompt: 'What does this function return when called as `f([3, 1, 4, 1, 5])`?\n\n```python\ndef f(lst):\n    for i in range(len(lst)):\n        for j in range(i + 1, len(lst)):\n            if lst[i] == lst[j]:\n                return True\n    return False\n```',
      choices: [
        { id: 'a', text: 'False' },
        { id: 'b', text: 'True' },
        { id: 'c', text: '1' },
        { id: 'd', text: 'None' },
      ],
      correctAnswer: 'b',
      explanation: 'The function checks every pair for duplicates. lst[1] == lst[3] (both 1), so it returns True. The nested loop is O(n²).',
    },
    {
      id: 'mt1-q3',
      type: 'multiple-choice',
      prompt: 'A binary search is performed on a sorted list of 64 elements. What is the maximum number of comparisons needed to determine the target is not present?',
      choices: [
        { id: 'a', text: '64' },
        { id: 'b', text: '32' },
        { id: 'c', text: '8' },
        { id: 'd', text: '6' },
      ],
      correctAnswer: 'd',
      explanation: 'Binary search is O(log n). log₂(64) = 6. At most 6 comparisons are needed — each step halves the search space.',
    },
    {
      id: 'mt1-q4',
      type: 'multiple-choice',
      prompt: 'What is the output?\n\n```python\ndef mystery(lst):\n    n = len(lst)\n    for i in range(n - 1):\n        min_idx = i\n        for j in range(i + 1, n):\n            if lst[j] < lst[min_idx]:\n                min_idx = j\n        lst[i], lst[min_idx] = lst[min_idx], lst[i]\n    return lst\n\nprint(mystery([4, 2, 7, 1]))\n```',
      choices: [
        { id: 'a', text: '[4, 2, 7, 1]' },
        { id: 'b', text: '[1, 2, 4, 7]' },
        { id: 'c', text: '[7, 4, 2, 1]' },
        { id: 'd', text: '[1, 4, 2, 7]' },
      ],
      correctAnswer: 'b',
      explanation: 'This is selection sort. Each pass selects the minimum of the remaining unsorted portion and swaps it into position. Result is [1, 2, 4, 7].',
    },
    {
      id: 'mt1-q5',
      type: 'multiple-choice',
      prompt: 'Which unit test assertion correctly checks that `divide(10, 0)` raises a `ZeroDivisionError`?',
      choices: [
        { id: 'a', text: 'self.assertEqual(divide(10, 0), ZeroDivisionError)' },
        { id: 'b', text: 'self.assertTrue(divide(10, 0))' },
        { id: 'c', text: 'with self.assertRaises(ZeroDivisionError):\n    divide(10, 0)' },
        { id: 'd', text: 'self.assertError(divide(10, 0))' },
      ],
      correctAnswer: 'c',
      explanation: 'assertRaises is used as a context manager: `with self.assertRaises(ExceptionType): call_that_raises()`. It passes if and only if the expected exception is raised inside the with block.',
    },

    // ── 10 Code Challenges ────────────────────────────────────────────────
    {
      id: 'mt1-q6',
      type: 'code-challenge',
      language: 'python',
      prompt: 'Write a function `safe_int(s)` that converts `s` to an integer and returns it. If conversion fails, catch the `ValueError` and return `0`. Print the results of `safe_int("42")`, `safe_int("hello")`, `safe_int("-7")`.',
      starterCode: '',
      expectedOutput: '42\n0\n-7',
      correctAnswer: '__code__',
      explanation: 'Use try/except ValueError: in the except block return 0, in the try block return int(s).',
    },
    {
      id: 'mt1-q7',
      type: 'code-challenge',
      language: 'python',
      prompt: 'Write a function `all_positive(lst)` that raises a `ValueError` with the message `"negative number found"` if any element is negative, otherwise returns `True`. Print `all_positive([1, 2, 3])`. Then catch the error from `all_positive([1, -2, 3])` and print the exception message.',
      starterCode: '',
      expectedOutput: 'True\nnegative number found',
      correctAnswer: '__code__',
      explanation: 'Iterate the list; if item < 0 raise ValueError("negative number found"). Wrap the second call in try/except ValueError as e: print(e).',
    },
    {
      id: 'mt1-q8',
      type: 'code-challenge',
      language: 'python',
      prompt: 'Write a function `count_ops(n)` that counts how many times the inner statement executes in a nested loop where the outer loop runs from 0 to n (exclusive) and the inner loop runs from 0 to the outer index (exclusive). Return the count. Print `count_ops(5)`.',
      starterCode: '',
      expectedOutput: '10',
      correctAnswer: '__code__',
      explanation: 'The outer loop runs i = 0..4. The inner loop runs j = 0..i. Total operations = 0+1+2+3+4 = 10. This is the triangle number pattern, giving O(n²/2) = O(n²) complexity.',
    },
    {
      id: 'mt1-q9',
      type: 'code-challenge',
      language: 'python',
      prompt: 'Write a function `linear_search(lst, target)` that returns the index of `target` in `lst`, or `-1` if not found. Print `linear_search([10, 30, 50, 70, 90], 50)` and `linear_search([10, 30, 50, 70, 90], 40)`.',
      starterCode: '',
      expectedOutput: '2\n-1',
      correctAnswer: '__code__',
      explanation: 'Iterate with enumerate(lst). When lst[i] == target return i. After the loop return -1.',
    },
    {
      id: 'mt1-q10',
      type: 'code-challenge',
      language: 'python',
      prompt: 'Write a function `binary_search(lst, target)` on a sorted list. Return the index if found, else `-1`. Print `binary_search([2, 5, 8, 12, 16, 23, 38], 23)` and `binary_search([2, 5, 8, 12, 16, 23, 38], 10)`.',
      starterCode: '',
      expectedOutput: '5\n-1',
      correctAnswer: '__code__',
      explanation: 'Use low=0, high=len(lst)-1. While low<=high: mid=(low+high)//2. If lst[mid]==target return mid. If lst[mid]<target set low=mid+1 else set high=mid-1. Return -1.',
    },
    {
      id: 'mt1-q11',
      type: 'code-challenge',
      language: 'python',
      prompt: 'Write a function `bubble_sort(lst)` that sorts a copy of the list in ascending order using bubble sort and returns it. Do not modify the original. Print `bubble_sort([64, 25, 12, 22, 11])`.',
      starterCode: '',
      expectedOutput: '[11, 12, 22, 25, 64]',
      correctAnswer: '__code__',
      explanation: 'Copy the list first (arr = lst[:]). Nested loops: outer i in range(n), inner j in range(n-i-1). Swap arr[j] and arr[j+1] if arr[j] > arr[j+1]. Return arr.',
    },
    {
      id: 'mt1-q12',
      type: 'code-challenge',
      language: 'python',
      prompt: 'Write a function `selection_sort(lst)` that sorts a copy of the list using selection sort and returns it. Print `selection_sort([29, 10, 14, 37, 13])`.',
      starterCode: '',
      expectedOutput: '[10, 13, 14, 29, 37]',
      correctAnswer: '__code__',
      explanation: 'Copy the list. For each position i, find the index of the minimum in arr[i:]. Swap arr[i] with arr[min_idx]. Return the sorted copy.',
    },
    {
      id: 'mt1-q13',
      type: 'code-challenge',
      language: 'python',
      prompt: 'Write a function `insertion_sort(lst)` that sorts a copy of the list using insertion sort and returns it. Print `insertion_sort([5, 2, 4, 6, 1, 3])`.',
      starterCode: '',
      expectedOutput: '[1, 2, 3, 4, 5, 6]',
      correctAnswer: '__code__',
      explanation: 'Copy the list. For i in range(1, n): key=arr[i], j=i-1. While j>=0 and arr[j]>key: arr[j+1]=arr[j], j-=1. Then arr[j+1]=key. Return the sorted copy.',
    },
    {
      id: 'mt1-q14',
      type: 'code-challenge',
      language: 'python',
      prompt: 'Write a function `find_min_max(lst)` that returns a tuple `(min_val, max_val)` using a single pass (one loop, no built-in min/max). Print `find_min_max([3, 1, 4, 1, 5, 9, 2, 6])`.',
      starterCode: '',
      expectedOutput: '(1, 9)',
      correctAnswer: '__code__',
      explanation: 'Initialise min_val=max_val=lst[0]. For each item: update min_val if item<min_val, update max_val if item>max_val. Return (min_val, max_val).',
    },
    {
      id: 'mt1-q15',
      type: 'code-challenge',
      language: 'python',
      prompt: 'Write a `Calculator` class with `__init__(self)` that sets `self.history = []`. Add a method `add(a, b)` that returns `a + b` and appends the result to history, and a method `last()` that returns the last result (or `None` if history is empty). Print `calc.add(3, 4)`, `calc.add(10, 5)`, `calc.last()`.',
      starterCode: '',
      expectedOutput: '7\n15\n15',
      correctAnswer: '__code__',
      explanation: 'add: result = a + b; self.history.append(result); return result. last: return self.history[-1] if self.history else None.',
    },
  ],
};

export default midterm1;
